bind r source-file ~/.config/tmux/tmux.conf

# Undercurl
# set -g default-terminal "${TERM}"
# set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
# set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
#
# set-environment -g COLORTERM "truecolor"

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:RGB"

set -g prefix C-s

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"
bind-key -r f  display-popup -E "~/.local/bin/tmux-sessionizer.sh"
# bind-key -n  M-t select-pane -U \;  resize-pane -Z
bind-key -n M-t run-shell "~/.config/tmux/toggle-terminal.sh"
bind-key -T copy-mode-vi M-t run-shell "~/.config/tmux/toggle-terminal.sh"

bind-key -n M-O run-shell "~/.config/tmux/toggle-opencode.sh"
bind-key -T copy-mode-vi M-O run-shell "~/.config/tmux/toggle-opencode.sh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'

# Theme
set -g @plugin 'catppuccin/tmux#latest'

# Put status on top
set -g status-position top

# Vim navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

# Tmuxifier
# set -g @plugin 'jimeh/tmuxifier'
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


bind w kill-session

bind -n M-h  previous-window
bind -n M-l next-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g status-right 'Continuum status: #{continuum_status}'
# set theme configs
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█"
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#(basename #{pane_current_path})"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
